Section 1 — Sales Features

In [ ]:
#01 — Load the Library
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [ ]:
#02 — Load the Clean Dataset
df = pd.read_csv(
    "../data/processed/clean_transactions.csv",
    parse_dates=["InvoiceDate"]
)

df.head()

C:\Users\محمد الرويلي\AppData\Local\Temp\ipykernel_6508\2441270399.py:1: DtypeWarning: Columns (0: InvoiceNo) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
#03 — Create Sales Amount
df["SalesAmount"] = (
    df["Quantity"] *
    df["UnitPrice"]
).round(2)

In [ ]:
#Verify
df[
    ["Quantity",
     "UnitPrice",
     "SalesAmount"]
].head()

   Quantity  UnitPrice  SalesAmount
0         6       2.55        15.30
1         6       3.39        20.34
2         8       2.75        22.00
3         6       3.39        20.34
4         6       3.39        20.34

In [ ]:
#04 — Generate Product Cost
np.random.seed(42)

unique_products = df["StockCode"].unique()

cost_ratios = pd.DataFrame({
    "StockCode": unique_products,
    "CostRatio": np.random.uniform(
        0.50,
        0.80,
        len(unique_products)
    )
})

In [ ]:
#05 — Merge it back
df = df.merge(
    cost_ratios,
    on="StockCode",
    how="left"
)

In [ ]:
#06 — Calculate Unit Cost
df["UnitCost"] = (
    df["UnitPrice"] *
    df["CostRatio"]
).round(2)

In [ ]:
#07 — Calculate Total Cost
df["TotalCost"] = (
    df["Quantity"] *
    df["UnitCost"]
).round(2)

In [ ]:
#08 — Calculate Profit
df["Profit"] = (
    df["SalesAmount"] -
    df["TotalCost"]
).round(2)

In [ ]:
#09 — Calculate Profit Margin % 
df["ProfitMargin"] = np.where(
    df["SalesAmount"] > 0,
    df["Profit"] / df["SalesAmount"],
    0
)

In [ ]:
#10 — Convert to percentage
df["ProfitMargin"] = (
    df["ProfitMargin"] * 100
).round(2)

In [ ]:
#11 — Validate the Features
df[
    [
        "SalesAmount",
        "UnitCost",
        "TotalCost",
        "Profit",
        "ProfitMargin"
    ]
].describe()

,SalesAmount,UnitCost,TotalCost,Profit,ProfitMargin
count,524878.000000,524878.000000,524878.000000,524878.000000,524878.000000
mean,20.275399,2.579939,13.126433,7.148966,35.061822
std,271.693566,24.864744,165.715973,107.675233,8.713813
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.900000,0.760000,2.480000,1.280000,27.480000
50%,9.920000,1.330000,6.240000,3.240000,34.940000
75%,17.700000,2.600000,11.680000,6.480000,42.620000
max,168469.600000,8967.200000,104483.550000,63986.050000,50.000000

In [ ]:
#12 — Inspect Sample Rows
df[
    [
        "Description",
        "Quantity",
        "UnitPrice",
        "SalesAmount",
        "UnitCost",
        "TotalCost",
        "Profit",
        "ProfitMargin"
    ]
].head(15)

,Description,Quantity,UnitPrice,SalesAmount,UnitCost,TotalCost,Profit,ProfitMargin
0,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,15.30,1.56,9.36,5.94,38.82
1,WHITE METAL LANTERN,6,3.39,20.34,2.66,15.96,4.38,21.53
2,CREAM CUPID HEARTS COAT HANGER,8,2.75,22.00,1.98,15.84,6.16,28.00
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,20.34,2.30,13.80,6.54,32.15
4,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,20.34,1.85,11.10,9.24,45.43
5,SET 7 BABUSHKA NESTING BOXES,2,7.65,15.30,4.18,8.36,6.94,45.36
6,GLASS STAR FROSTED T-LIGHT HOLDER,6,4.25,25.50,2.20,13.20,12.30,48.24
7,HAND WARMER UNION JACK,6,1.85,11.10,1.41,8.46,2.64,23.78
8,HAND WARMER RED POLKA DOT,6,1.85,11.10,1.26,7.56,3.54,31.89
9,ASSORTED COLOUR BIRD ORNAMENT,32,1.69,54.08,1.20,38.40,15.68,28.99
10,POPPY'S PLAYHOUSE BEDROOM,6,2.10,12.60,1.06,6.36,6.24,49.52
11,POPPY'S PLAYHOUSE KITCHEN,6,2.10,12.60,1.66,9.96,2.64,20.95
12,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,3.75,30.00,2.81,22.48,7.52,25.07
13,IVORY KNITTED MUG COSY,6,1.65,9.90,0.93,5.58,4.32,43.64
14,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,4.25,25.50,2.36,14.16,11.34,44.47

In [ ]:
#13 — Save the Enriched Dataset
df.to_csv(
    "../data/processed/transactions_enriched.csv",
    index=False
)

Section 2 — Date Features

In [ ]:
#01 — Create Invoice Date Only
df["InvoiceDateOnly"] = df["InvoiceDate"].dt.date

In [ ]:
#02 — Year
df["Year"] = df["InvoiceDate"].dt.year

In [ ]:
#03 — Quarter
df["Quarter"] = "Q" + df["InvoiceDate"].dt.quarter.astype(str)

In [ ]:
#04 — Month Number
df["Month"]=df["InvoiceDate"].dt.month

In [ ]:
#05 — Month Name
df["MonthName"] = df["InvoiceDate"].dt.month_name()

In [ ]:
#06 — Month Abbreviation
df["MonthShort"] = df["InvoiceDate"].dt.strftime("%b")

In [ ]:
#07 — Week Number
df["Week"] = df["InvoiceDate"].dt.isocalendar().week

In [ ]:
#08 — Day of Month
df["Day"] = df["InvoiceDate"].dt.day

In [ ]:
#09 — Day Name 
df["DayName"] = df["InvoiceDate"].dt.day_name()

In [ ]:
#10 — Day Number
df["DayOfWeek"] = df["InvoiceDate"].dt.dayofweek

In [ ]:
#11 — Weekend Flag
df["IsWeekend"] = df["DayOfWeek"] >= 5

In [ ]:
#12 — Season

#Create a function
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

#apply it
df["Season"] = df["Month"].apply(get_season)

In [ ]:
#13 — Simple improvment (YearMonth)
df["YearMonth"] = (
    df["InvoiceDate"].dt.strftime("%Y-%m")
)

In [ ]:
#14 — Validation
df[
    [
        "InvoiceDate",
        "InvoiceDateOnly",
        "Year",
        "Quarter",
        "Month",
        "MonthName",
        "Week",
        "Day",
        "DayName",
        "IsWeekend",
        "Season"
    ]
].head(15)

,InvoiceDate,InvoiceDateOnly,Year,Quarter,Month,MonthName,Week,Day,DayName,IsWeekend,Season
0,2010-12-01 08:26:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
1,2010-12-01 08:26:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
2,2010-12-01 08:26:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
3,2010-12-01 08:26:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
4,2010-12-01 08:26:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
5,2010-12-01 08:26:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
6,2010-12-01 08:26:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
7,2010-12-01 08:28:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
8,2010-12-01 08:28:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
9,2010-12-01 08:34:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
10,2010-12-01 08:34:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
11,2010-12-01 08:34:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
12,2010-12-01 08:34:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
13,2010-12-01 08:34:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter
14,2010-12-01 08:34:00,2010-12-01,2010,Q4,12,December,48,1,Wednesday,False,Winter

In [ ]:
#15 — Save progress
df.to_csv(
    "../data/processed/transactions_enriched.csv",
    index=False
)

Section 3 — Business Rule Features

In [ ]:
#01 — DiscountPercent
np.random.seed(42)

discounts = [0, 5, 10, 15, 20]

probabilities = [
    0.70,
    0.15,
    0.08,
    0.05,
    0.02
]

df["DiscountPercent"] = np.random.choice(
    discounts,
    size=len(df),
    p=probabilities
)

#Validate
df["DiscountPercent"].value_counts(normalize=True) * 100

DiscountPercent
0     70.031131
5     14.970717
10     8.010814
15     4.992208
20     1.995130
Name: proportion, dtype: float64

In [ ]:
#02 — PromotionApplied
df["PromotionApplied"] = (
    df["DiscountPercent"] > 0
)

In [ ]:
#03 — Promotion Type
#first create the column 
df["PromotionType"] = "No Promotion"

#update only discounted sales
promotion_types = [
    "Flash Sale",
    "Seasonal Sale",
    "Clearance",
    "Member Discount"
]

mask = df["PromotionApplied"]

df.loc[
    mask,
    "PromotionType"
] = np.random.choice(
    promotion_types,
    size=mask.sum()
)

#Validate
df["PromotionType"].value_counts()

PromotionType
No Promotion       367578
Clearance           39459
Flash Sale          39444
Seasonal Sale       39236
Member Discount     39161
Name: count, dtype: int64

In [ ]:
#04 — Order Size
conditions = [
    df["SalesAmount"] < 50,
    df["SalesAmount"].between(50, 200),
    df["SalesAmount"] > 200
]

choices = [
    "Small",
    "Medium",
    "Large"
]

df["OrderSize"] = np.select(
    conditions,
    choices,
    default="Small"
)

In [ ]:
#05 — Sales Channel
df["SalesChannel"] = np.random.choice(
    [
        "Online",
        "In-Store"
    ],
    size=len(df),
    p=[0.60, 0.40]
)

In [ ]:
#06 — Payment Method
payment_methods = [
    "Credit Card",
    "Debit Card",
    "PayPal",
    "Bank Transfer",
    "Cash"
]

payment_probabilities = [
    0.50,
    0.20,
    0.15,
    0.10,
    0.05
]

df["PaymentMethod"] = np.random.choice(
    payment_methods,
    size=len(df),
    p=payment_probabilities
)

In [ ]:
#07 — Shipping Priority
shipping = [
    "Standard",
    "Express",
    "Same Day"
]

shipping_prob = [
    0.65,
    0.25,
    0.10
]

df["ShippingPriority"] = np.random.choice(
    shipping,
    size=len(df),
    p=shipping_prob
)

In [ ]:
#08 — Validation
df[
    [
        "SalesAmount",
        "DiscountPercent",
        "PromotionApplied",
        "PromotionType",
        "OrderSize",
        "SalesChannel",
        "PaymentMethod",
        "ShippingPriority"
    ]
].head(20)

,SalesAmount,DiscountPercent,PromotionApplied,PromotionType,OrderSize,SalesChannel,PaymentMethod,ShippingPriority
0,15.30,0,False,No Promotion,Small,Online,Credit Card,Standard
1,20.34,15,True,Flash Sale,Small,In-Store,Cash,Standard
2,22.00,5,True,Member Discount,Small,Online,PayPal,Same Day
3,20.34,0,False,No Promotion,Small,In-Store,Credit Card,Same Day
4,20.34,0,False,No Promotion,Small,In-Store,Credit Card,Express
5,15.30,0,False,No Promotion,Small,Online,Cash,Standard
6,25.50,0,False,No Promotion,Small,Online,PayPal,Express
7,11.10,10,True,Member Discount,Small,In-Store,Bank Transfer,Same Day
8,11.10,0,False,No Promotion,Small,Online,Credit Card,Standard
9,54.08,5,True,Clearance,Medium,In-Store,Credit Card,Express
10,12.60,0,False,No Promotion,Small,In-Store,Debit Card,Standard
11,12.60,15,True,Member Discount,Small,Online,Credit Card,Standard
12,30.00,5,True,Flash Sale,Small,In-Store,Credit Card,Standard
13,9.90,0,False,No Promotion,Small,In-Store,Credit Card,Standard
14,25.50,0,False,No Promotion,Small,Online,Debit Card,Express
15,14.85,0,False,No Promotion,Small,Online,Bank Transfer,Express
16,19.90,0,False,No Promotion,Small,In-Store,PayPal,Standard
17,17.85,0,False,No Promotion,Small,Online,PayPal,Same Day
18,17.85,0,False,No Promotion,Small,Online,Credit Card,Standard
19,31.80,0,False,No Promotion,Small,In-Store,Credit Card,Standard

In [ ]:
#09 — Save the Dataset
df.to_csv(
    "../data/processed/transactions_enriched.csv",
    index=False
)

Section 4 — Customer Features

In [ ]:
#01 — Create IsGuestCustomer
df["IsGuestCustomer"] = df["CustomerID"].isna()

In [ ]:
#02 — Validate
df["IsGuestCustomer"].value_counts()

IsGuestCustomer
False    392692
True     132186
Name: count, dtype: int64